BartlettBrands/bartlettbrands-com

public_html/index.php
Removed BeautyBooked quote and updated with new Biossance quote.
=> Updated client quotes.

public_html/assets/css/styles.css
@carolinapistone approve per favore
=> modal on safari needed the overflow removed.

public_html/randfbrand.php
=> Reorganized R and F per Rebecca's request.

public_html/index.php
=> Changed creative to strategic on homepage.

public_html/biossance.php
Nathan Akers is a wonderful teacher. Da best. Also, added a video.
=> Added Biossance video. Woooooo yeah.

public_html/biossance.php
Caro, remember that this is temporary and will be changed back at the end of the week. You probably won't see this message again, so you'll probably forget. Maybe set a calendar reminder or something. But yeah, all good to go!
=> Switched order of video for email.

public_html/includes/html-app-footer.php, public_html/includes/html-app-header.php
=> Add Gooogle Tag Manager, Clean Header and Footer

public_html/index.php
Snappy and smooth AF. 'Git' it, girl (pun intended).
=> Updated brand statement.

public_html/index.php
=> R requested line break removed.

public_html/includes/functions.php
=> fix white screen

public_html/biossance.php
=> Moved video down on page.

public_html/includes/site-data.php, public_html/index.php
=> Hid Paula's Choice.

public_html/index.php
=> Swapped Chris's statement for Stef's.

public_html/includes/site-data.php
=> Updating Gift Good copy.

public_html/giftgood.php
=> Rebecca always has last minute changes.

public_html/includes/site-data.php
=> Updated Rebecca's tumblr url.

public_html/index.php
=> RB feedback.

public_html/index.php
=> Added Eco-Warrior email

public_html/includes/site-data.php
=> Removed Ao site link.

includes/site-data.php
=> Superkin copy edit
